import styles from "../styles/layout/root.module.scss"
import { MantineProvider } from "@mantine/core"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import Navbar from "../_components/navbar"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const links = [
    { name: 'About', key: 0 },
    { name: 'Projects', key: 1 },
    { name: 'Contact', key: 2 },
  ]
  return (

    <html lang="en">

      <body className={styles.page}>
       
          <Navbar links={links} />
          {children}
      </body>
    </html>
  )
}
